const DISPLAY_MEDIUM_SIZE = 768;
const DISPLAY_DESKTOP_SIZE = 1280;
const DISPLAY_MOBILE_SIZE = 767;

const DISPLAY_DESKTOP_RENDER = 1279;
const COUNT_MOBILE_SIZE_ADD_MOVIE = 2;
const COUNT_DESKTOP_SIZE_ADD_MOVIE = 3;

const QUANTITY_MOVIES_FOR_MEDIUM_SIZE = 8;
const QUANTITY_MOVIES_FOR_MOBILE_SIZE = 5;
const QUANTITY_MOVIES_FOR_DESKTOP_SIZE = 12;

const DURATION_SHORT_MOVIE = 40;

export {
    DISPLAY_MEDIUM_SIZE,
    DISPLAY_DESKTOP_SIZE,
    DISPLAY_MOBILE_SIZE,
    DISPLAY_DESKTOP_RENDER,
    COUNT_MOBILE_SIZE_ADD_MOVIE,
    COUNT_DESKTOP_SIZE_ADD_MOVIE,
    DURATION_SHORT_MOVIE,
    QUANTITY_MOVIES_FOR_MEDIUM_SIZE,
    QUANTITY_MOVIES_FOR_MOBILE_SIZE,
    QUANTITY_MOVIES_FOR_DESKTOP_SIZE
};